repos:
  # autoflake → remove unused imports/variables first
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-all-unused-imports", "--remove-unused-variables"]

  # isort → sort remaining imports
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=100"]

  # black → format everything consistently
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=100"]


  # Strip output from Jupyter notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        files: \.ipynb$

  # # flake8 → final linting pass
  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.1.1
  #   hooks:
  #     - id: flake8
  #       args: ["--max-line-length=100"]
